# Generated by Django 4.2.23 on 2025-09-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('jarayyonda', 'Jarayyonda'), ('tugallangan', 'Tugallangan')], default='yangi', max_length=255),
        ),
    ]
