# Generated by Django 4.2.23 on 2025-08-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_admin',
        ),
    ]
