# Generated by Django 4.2.23 on 2025-08-27 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_tasks_created_by_alter_tasks_doer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_create', to=settings.AUTH_USER_MODEL),
        ),
    ]
